### PR TITLE
add travis configuration file

### PR DESCRIPTION
**Pull request by szabgab**
If you decide to accept this PR please enable  Travis-CI for this repo at https://travis-ci.org/

### CODE REVIEW

**Comment by trwyant** [comment]
A very belated thanks for the pull request. I have spent the last couple months in crisis mode, and have not had the energy to take on a new-to-me technology. But I appreciate the jump-start you have given me for when things get back to something more like normal.

**Comment by szabgab** [comment]
:+1: no problem, we are all get too busy from time to time

**Comment by trwyant** [comment]
Thanks again for the jump-start. I am going to accept this PR _pro forma_, though the .travis.yml I have worked out is different, and probably over-complicated.

**Comment by szabgab** [comment]
Since the time I sent this PR I started to use GitHub Actions for CI. You might be interested to set that up in addition or instead of Travis.

**Pull request merged**
